// <auto-generated />
namespace eLearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_instructorandcourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_instructorandcourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202309141847148_mig_instructorandcourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
